apiVersion: apps/v1
kind: Deployment
metadata:
  name: encheres-royale-front
  labels:
    app: encheres-royale-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encheres-royale-front
  template:
    metadata:
      labels:
        app: encheres-royale-front
    spec:
      serviceAccountName: frontend-service-account
      containers:
      - name: front
        image: abderrezak77/encheres-royale-front:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: LoadBalancer
  selector:
    app: encheres-royale-front
  ports:
  - port: 80
    targetPort: 80
